version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/initialize-db.sql:/docker-entrypoint-initdb.d/initialize-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp -d chatapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://chatapp:chatapp_password@postgres:5432/chatapp
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatapp
      - DB_USER=chatapp
      - DB_PASSWORD=chatapp_password
    command: npm start

  ui:
    build: ./ui
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: